default: deny | allow

allow:
    file:
        # File path specifiers:
        # - literal
        # - regex
        # - subpath
        - all
        - literal: /tmp/a
        - regex: /tmp/b
        - subpath: /tmp/c

        chroot:
            - all
            - literal: /tmp/a
            - regex: /tmp/b
            - subpath: /tmp/c

        - ioctl
        - revoke
        read:
            - all
            - data
            - metadata
            - xattr
        write:
            - all
            - data
            - flags
            - mode
            - mount
            - owner
            - setugid
            - time
            - unmount
            - xattr
    ipc:
        - all
        posix:
            - all
            - sem
            - shm
        sysv:
            - all
            - msg
            - sem
            - shm
        mach:
            - all
            - bootstrap
            - lookup
            - task-name
            priv:
                - all
                - host-post
                - task-port
    network:
        # Network protocol qualifiers:
        # - unix
        # - ip / ip4 / ip6
        # - tcp / tcp4 / tcp6
        # - udp / udp4 / udp6
        - all
        - inbound:
            tcp: "*:8080"
        - outbound:
            tcp: "*:443"
        - bind
    process:
        - all
        - exec
        - fork
    sec:
        # Modifiers:
        # - no-log
        # - no-sandbox
        # - no-profile (same as no-sandbox)
        # - send-signal
        - send-signal
        - signal
        - job-creation
        - mach-per-user-lookup
        sysctl:
            - all
            - read
            - write
        system:
            - all
            - acct
            - audit
            - fsctl
            - lcid
            - mac-label
            - nfssvc
            - reboot
            - set-time
            - socket
            - swap
            - write-bootstrap

deny:
    # Has the same structure as allow:

# `with` modifier 
#  Applicable to any rule.
# - with: report     (allow but log)
# - with: no-report  (suppress logging)

